# Generated by Django 5.2.4 on 2025-07-20 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        help_text="Complete name as preferred by the person",
                        max_length=200,
                    ),
                ),
                (
                    "given_names",
                    models.CharField(
                        blank=True,
                        help_text="Given/first names (space-separated if multiple)",
                        max_length=150,
                    ),
                ),
                (
                    "family_names",
                    models.CharField(
                        blank=True,
                        help_text="Family/surname(s) (space-separated if multiple)",
                        max_length=150,
                    ),
                ),
                (
                    "preferred_name",
                    models.CharField(
                        blank=True,
                        help_text="Name to use in conversation (nickname, chosen name, etc.)",
                        max_length=100,
                    ),
                ),
                (
                    "patronymic",
                    models.CharField(
                        blank=True,
                        help_text="Patronymic name (father's name derivative)",
                        max_length=100,
                    ),
                ),
                (
                    "matronymic",
                    models.CharField(
                        blank=True,
                        help_text="Matronymic name (mother's name derivative)",
                        max_length=100,
                    ),
                ),
                (
                    "middle_names",
                    models.CharField(
                        blank=True,
                        help_text="Middle names (space-separated if multiple)",
                        max_length=150,
                    ),
                ),
                (
                    "suffix",
                    models.CharField(
                        blank=True,
                        help_text="Name suffix (Jr., Sr., III, etc.)",
                        max_length=20,
                    ),
                ),
                (
                    "prefix",
                    models.CharField(
                        blank=True,
                        help_text="Name prefix (Dr., Prof., etc.)",
                        max_length=20,
                    ),
                ),
                (
                    "legal_name",
                    models.CharField(
                        blank=True,
                        help_text="Full legal name as it appears on government documents",
                        max_length=200,
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "gender_identity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("woman", "Woman"),
                            ("man", "Man"),
                            ("non_binary", "Non-binary"),
                            ("genderfluid", "Genderfluid"),
                            ("agender", "Agender"),
                            ("questioning", "Questioning"),
                            ("other", "Other"),
                            ("prefer_not_to_say", "Prefer not to say"),
                        ],
                        help_text="Self-identified gender",
                        max_length=20,
                    ),
                ),
                (
                    "biological_sex",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("female", "Female"),
                            ("male", "Male"),
                            ("intersex", "Intersex"),
                            ("unknown", "Unknown"),
                            ("prefer_not_to_say", "Prefer not to say"),
                        ],
                        help_text="Sex assigned at birth",
                        max_length=20,
                    ),
                ),
                (
                    "pronouns",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("she_her", "She/Her"),
                            ("he_him", "He/Him"),
                            ("they_them", "They/Them"),
                            ("xe_xir", "Xe/Xir"),
                            ("ze_zir", "Ze/Zir"),
                            ("other", "Other"),
                            ("ask_me", "Ask me"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "custom_pronouns",
                    models.CharField(
                        blank=True,
                        help_text="Custom pronouns (e.g., 'fae/faer')",
                        max_length=50,
                    ),
                ),
                (
                    "legal_sex",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("female", "Female"),
                            ("male", "Male"),
                            ("intersex", "Intersex"),
                            ("unknown", "Unknown"),
                            ("prefer_not_to_say", "Prefer not to say"),
                        ],
                        help_text="Sex marker on legal documents",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this record",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="persons_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        help_text="User who last updated this record",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="persons_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "person",
            },
        ),
    ]
