# Generated by Django 5.2.4 on 2025-07-20 16:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patient", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="pronouns",
            field=models.CharField(
                blank=True,
                choices=[
                    ("she_her", "She/Her"),
                    ("he_him", "He/Him"),
                    ("they_them", "They/Them"),
                    ("xe_xir", "Xe/Xir"),
                    ("ze_zir", "Ze/Zir"),
                    ("other", "Other"),
                    ("ask_me", "Ask me"),
                ],
                help_text="Preferred pronouns for the person (e.g., 'she/her', 'he/him', 'they/them')",
                max_length=15,
            ),
        ),
    ]
