# Generated by Django 5.2.4 on 2025-07-20 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("patient", "0002_alter_person_pronouns"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientRiskAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chads_score", models.IntegerField()),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="patient.person"
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient Risk Assessment",
                "verbose_name_plural": "Patient Risk Assessments",
                "ordering": ["-chads_score"],
                "unique_together": {("person", "chads_score")},
            },
        ),
    ]
