# Generated by Django 5.2.4 on 2025-07-20 17:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patient_risk", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="patientriskassessment",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Patient Risk Assessment",
                "verbose_name_plural": "Patient Risk Assessments",
            },
        ),
        migrations.AddField(
            model_name="patientriskassessment",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="patientriskassessment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="patientriskassessment",
            name="chads_score",
            field=models.IntegerField(
                help_text="CHADS2-VASc score (0-9) for stroke risk assessment"
            ),
        ),
    ]
