# Generated by Django 5.2.4 on 2025-07-27 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patient_risk", "0002_alter_patientriskassessment_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientriskassessment",
            name="contraindication_flags",
            field=models.JSONField(
                default=dict, help_text="Clinical contraindications per CMS-134v8. This"
            ),
        ),
        migrations.AddField(
            model_name="patientriskassessment",
            name="hasbled_score",
            field=models.IntegerField(
                default=0, help_text="HAS-BLED score (0-9) for bleeding risk assessment"
            ),
        ),
        migrations.AddField(
            model_name="patientriskassessment",
            name="qrisk3_value",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="QRISK3 score for cardiovascular risk",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name="patientriskassessment",
            name="chads_score",
            field=models.IntegerField(
                default=0,
                help_text="CHADS2-VASc score (0-9) for stroke risk assessment",
            ),
        ),
    ]
