# Generated by Django 5.2.4 on 2025-07-27 18:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patient_risk", "0003_patientriskassessment_contraindication_flags_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientriskassessment",
            name="chads_score",
            field=models.IntegerField(
                default=0,
                help_text="CHADS2-VASc score (0-9) for stroke risk assessment",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(9),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="patientriskassessment",
            name="contraindication_flags",
            field=models.JSONField(
                default=dict,
                help_text="Clinical contraindications per CMS-134v8 guidelines",
            ),
        ),
        migrations.AlterField(
            model_name="patientriskassessment",
            name="hasbled_score",
            field=models.IntegerField(
                default=0,
                help_text="HAS-BLED score (0-9) for bleeding risk assessment",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(9),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="patientriskassessment",
            name="qrisk3_value",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="QRISK3 score for cardiovascular risk",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(100.0),
                ],
            ),
        ),
    ]
