# Generated by Django 5.2.4 on 2025-08-09 17:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("patient_risk", "0004_alter_patientriskassessment_chads_score_and_more"),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name="patientriskassessment",
            table_comment="Cardiovascular risk calculations per Joint Commission PC-03. Owner: CardioTeam@example.com",
        ),
    ]
